# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineitem',
            options={'verbose_name': '条目', 'verbose_name_plural': '条目'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-createtime'], 'verbose_name': '商品信息', 'verbose_name_plural': '商品信息'},
        ),
        migrations.AlterModelTable(
            name='lineitem',
            table='line_item',
        ),
    ]
