# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cart', '0002_auto_20180624_1940'),
    ]

    operations = [
    ]
